FirstCommit
AlinBivolan/EmojiPicker-Chat pull request #1
Opened 2022-06-02 08:30 UTC by AlinBivolan

2022-06-06 09:01 UTC, andreipop02 requested changes

2022-06-06 09:01 UTC, andreipop02 commented on src/Display/Display.js
> +        </div>
make this self-close tag, as you dont wrap anything

2022-06-06 09:01 UTC, andreipop02 commented on src/TextInput/EmojiModal.js
> +import React from "react";
make a single import for those 2, they are both from "react"

2022-06-16 13:09 UTC, catalinracz requested changes

2022-06-16 13:09 UTC, catalinracz commented on src/constants/arrays.js
> +// export const Category = [
remove if not used anymore

2022-06-16 13:09 UTC, andreipop02 approved these changes

2022-06-16 13:09 UTC, andreipop02 commented on src/TextInput/Input.js
> +  const modalHandler = () => {
name it more specifically ( something like: closeEmojiModal )

2022-06-16 13:09 UTC, andreipop02 commented on src/TextInput/Input.js
> +  const emojiHandler = () => {
name it more specifically ( something like: openEmojiModal )

2022-06-16 13:09 UTC, andreipop02 commented on src/TextInput/ModalContent/Categories.js
> +            <h1 className={classes.category_name}>Recent Used</h1>
Add this to a strings file and import from there (ex: strings.recentUsed)

2022-06-16 13:09 UTC, andreipop02 commented on src/TextInput/ModalContent/Emoji.js
> +        {category}{" "}
What do we need "{" "}" for?

2022-06-16 13:09 UTC, andreipop02 commented on src/TextInput/Input.js
> +        placeholder="Your Messages..."
add to strings file

2022-06-16 13:11 UTC, catalinracz commented
<img width="571" alt="Screenshot 2022-06-16 at 4 10 10 pm" src="https://user-images.githubusercontent.com/80832598/174076949-3eeb8630-8a57-45cf-a2de-44e657ad6335.png">
The picker comes over the input on smaller screens.

2023-01-12 01:07 UTC, merged